apiVersion: v1
kind: Service
metadata:
  name: object-detection-service
  namespace: ass1
spec:
  type: NodePort
  selector:
    app: object-detection-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30000
